package main

import "google.golang.org/protobuf/compiler/protogen"

const (
	importsTemplate = ""
)

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	filename := file.GeneratedFilenamePrefix + ".go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by itcourse-protoc-go-templator. DO NOT EDIT.")

	g.P()
	appendPackageName(g, file.GoPackageName)
	g.P()
	appendImports(g)
	g.P()
	appendFunctionDeclaration(g)
	g.P()
}

func appendPackageName(g *protogen.GeneratedFile, packageName protogen.GoPackageName) {
	g.P("package ", file.GoPackageName)
}

func appendImports(g *protogen.GeneratedFile) {
	g.P("import (")
	g.P(`	"context"`)
	g.P(`	"fmt"`)
	g.P(`	pb ""`)
	g.P(")")
}

func appendFunctionDeclaration(g *protogen.GeneratedFile) {}
